services:
  - type: web
    name: third-party-vendor-assessment
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: third-party-vendor-db
          property: connectionString

databases:
  - name: third-party-vendor-db
    databaseName: third_party_vendor
    user: third_party_vendor_user 